site_name: RINGMesh - Platform for geological models
docs_dir: 'docs'
site_description: 'RINGMesh is a C++ open-source platform for manipulating meshes of geological models.'

markdown_extensions:
    - extra  # allow markdown in <div markdown="1">
    - fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages

repo_url: https://github.com/ringmesh/ringmesh
remote_name: origin

nav:
    - '_Home': index.md
    - 'Try !':
        - 'Try online': try/try_online.md
        - 'Get started': try/installation.md
        - 'Doxygen documentation': try/documentation.md
        - 'Tutorials': try/tutorials.md
        - '_Geomodel Basics': try/tutorials/geomodel/geomodel-basics.md
        - '_Configure Compile': try/tutorials/configure_compile_ringmesh.md

    - Features:
        - 'GeoModel': features/geomodel.md
        - 'Mesh': features/mesh.md
        - 'Validity': features/validity.md
        - 'Supported file formats': features/file_formats.md
    - Gallery: gallery.md
    - Glossary: glossary.md
    - Download: download.md
    - About: about.md

copyright: Copyright &copy; 2018, Association Scientifique pour la Géologie et ses Applications <a href="http://asgageol.univ-lorraine.fr/">(ASGA)</a>
theme:
    name: null
    custom_dir: ringmesh_theme

extra:
    site_name_short: RINGMesh
