site_name: RINGMesh
docs_dir: 'docs'

markdown_extensions:
    - extra  # allow markdown in <div markdown="1">
    - fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages

repo_url: https://github.com/ringmesh/ringmesh
remote_name: github

pages:
    - Home: index.md
    - 'Try !':
        - 'Try online': try/try_online.md
        - 'Installation': try/installation.md
        - 'Doxygen documentation': try/documentation.md
        - 'Tutorials': try/tutorials.md
    - Features:
        - 'The GeoModel object': features/geomodel.md
        - 'Supported file formats': features/file_formats.md
        - 'Mesh Handling': features/mesh_handling.md
        - 'Viewer': features/viewer.md
    - Gallery: gallery.md
    - Download: download.md
    - About: about.md

include_next_prev: false  # turn off next/previous buttons
theme_dir: cinder

